### ISSUE TITLE
Adding ChefSpec Matcher

### ISSUE THREAD

**Issue by ghost** [chef-cookbooks/rubygems#17]
### Cookbook version
1.0.4

### Chef-client version
12 & 13

### Platform Details
All 

### Scenario:
It looks like for the custom resources, a ChefSpec matcher is not included.  When doing ChefSpec testing, a developer has to provide their own matcher.

**Comment by iennae** [comment]
With ChefSpec 7.1.0 this will no longer be needed. Check out https://github.com/sethvargo/chefspec#automatic-matchers. The release should drop shortly.

**Comment by iennae** [comment]
ChefSpec 7.1.0 has been released with the automatic matchers.
